String TileMap[H] = {
	"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
	"0                                                                                                                                         0          0",
	"0                                                                                    w                                                    0  w       0",
	"0                   w                                  w                   w                                                     w        0          0",
	"0                                      w                                                                   w                              0          0",
	"0                                                                                                                       ww                0          0",
	"0                      c                                                                       w                                          0          0",
	"0                                                                       r                                                                 00         0",
	"0                                                                      rr                                                              m  20         0",
	"0                                                                     rrr      kckck                                                      20         0",
	"0               c    kckck                                           rrrr                                                                 20         0",
	"0                                      t0                           rrrrr                          t0                                     20         0",
	"0G                                     00              t0          rrrrrr                          00         G                           20         0",
	"0           d    g       d             00              00         rrrrrrr  d                   g   00   d         t0     d                20         0",
	"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP    PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
	"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP    PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
	"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPxxPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPxxxxPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
	"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
	"0                                                                                                                                         0          0",
	"0                                                                                    w                                                    0  w       0",
	"0                   w                                  w                   w                                                     w        0          0",
	"0                                      w                                                                   w                              0          0",
	"0                                    kckck                                                                              ww                0          0",
	"0                      c                                                                       w                                          0          0",
	"0                            kckck                                                                                                        00         0",
	"0                                                                      rr                                                              m  30         0",
	"0      c                                                              rrr      kckck                                                      30         0",
	"0      c        c    kckck                                                                                 rrr      rr                    30         0",
	"0                                                                                                  t0     rrrr            kkk             30         0",
	"0G                                     t0              t0          rrrrrr                          00    rrrrrG                           30         0",
	"0           d    g       d             00              00         rrrrrrr  d                   g   00   rrrrrr    t0     d                30         0",
	"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP    PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
	"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP    PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
	"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPxxPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPxxxxPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
	"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
	"0                                                                                                                                         0          0",
	"0                                                                                    w                                                    0  w       0",
	"0                   w                                  w                   w                                                     w        0          0",
	"0                                      w                                                                   w                              0          0",
	"0                                    kckck                                                                              ww                0          0",
	"0                      c                                                                       w                                          0          0",
	"0                            kckck                                                                                                        00         0",
	"0                                                                                                                                      m  40         0",
	"0      c                                                                       kckck                                                      40         0",
	"0      c        c    kkkkk                                                                                 rrr      rr                    40         0",
	"0                                                                                                  t0     rrrr            kkk             40         0",
	"0G                                     t0              t0          rrrrrr                          00    rrrrrG                           40         0",
	"0           d    g       d             00              00          rrrrrr  d                   g   00   rrrrrr    t0     d                40         0",
	"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP    PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
	"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP    PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
	"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPxxPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPxxxxPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
};  